import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-950 text-white">
        <nav className="p-4 border-b border-gray-800 flex gap-4">
          <a href="/" className="font-bold text-white hover:text-gray-300">Distribution</a>
          <a href="/forensics" className="text-gray-400 hover:text-white">Forensics</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
